"""Local-first PR body preparation from evolution run reports."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any, Callable

import click

Runner = Callable[[list[str]], None]


def _target(report: dict[str, Any]) -> str:
    return str(report.get("target_name") or report.get("skill_name") or "artifact")


def _fmt_score(value: Any) -> str:
    return "n/a" if value is None else f"{float(value):.3f}"


def _fmt_delta(value: Any) -> str:
    return "n/a" if value is None else f"{float(value):+.3f}"


def build_pr_title(report: dict[str, Any]) -> str:
    """Build a deterministic PR title from a run report."""
    artifact_type = report.get("artifact_type", "artifact")
    return f"chore: promote evolved {_target(report)} {artifact_type}"


def _constraint_lines(report: dict[str, Any]) -> list[str]:
    constraints = report.get("constraint_results") or []
    if not constraints:
        return ["- No constraint details recorded."]
    lines = []
    for result in constraints:
        icon = "PASS" if result.get("passed") else "FAIL"
        lines.append(
            f"- {icon} `{result.get('constraint_name', 'unknown')}`: "
            f"{result.get('message', '')}"
        )
    return lines


def _benchmark_lines(report: dict[str, Any]) -> list[str]:
    gate = report.get("benchmark_gate") or report.get("benchmark_gate_result")
    if not gate:
        return ["- No benchmark gate result attached to this report."]
    lines = [f"- Passed: {gate.get('passed')}"]
    failures = gate.get("failures") or []
    if failures:
        lines.append("- Failures:")
        lines.extend(f"  - {failure}" for failure in failures)
    return lines


def build_pr_body(report: dict[str, Any]) -> str:
    """Build a deterministic, review-ready PR body from a run report."""
    target = _target(report)
    title = build_pr_title(report)
    baseline_size = report.get("baseline_size", "n/a")
    evolved_size = report.get("evolved_size", report.get("optimized_size", "n/a"))
    artifact_growth = "n/a"
    if isinstance(baseline_size, int | float) and baseline_size:
        artifact_growth = f"{((float(evolved_size) - float(baseline_size)) / float(baseline_size)):+.1%}"

    lines = [
        "## Summary",
        "",
        f"Promotes an evolved `{target}` {report.get('artifact_type', 'artifact')} generated by hermes-agent-self-evolution.",
        "",
        "## Before / After Metrics",
        "",
        "| Metric | Baseline | Evolved | Change |",
        "| --- | ---: | ---: | ---: |",
        f"| Holdout score | {_fmt_score(report.get('baseline_score'))} | {_fmt_score(report.get('evolved_score'))} | {_fmt_delta(report.get('improvement'))} |",
        f"| Artifact size | {baseline_size} | {evolved_size} | {artifact_growth} |",
        "",
        "## Dataset / Models",
        "",
        f"- Dataset source: `{report.get('dataset_source', 'unknown')}`",
        f"- Split counts: `{json.dumps(report.get('split_counts', {}), sort_keys=True)}`",
        f"- Optimizer model: `{report.get('optimizer_model', 'unknown')}`",
        f"- Eval model: `{report.get('eval_model', 'unknown')}`",
        "",
        "## Artifacts",
        "",
        f"- Baseline hash: `{report.get('baseline_hash', 'unknown')}`",
        f"- Evolved hash: `{report.get('evolved_hash', report.get('optimized_hash', 'unknown'))}`",
        f"- Run report: `{report.get('report_path', 'unknown')}`",
        f"- Diff: `{report.get('diff_path', 'unknown')}`",
        "",
        "## Constraints",
        "",
        f"- Aggregate passed: {report.get('constraints_passed')}",
        *_constraint_lines(report),
        "",
        "## Benchmark Gate",
        "",
        *_benchmark_lines(report),
        "",
        "## Risk Notes",
        "",
        "- Generated artifact should be reviewed before merge.",
        "- Confirm no private session data or secrets are present in the diff.",
        "- Confirm benchmark gate output, if absent here, before promotion.",
        "",
        "## Rollback",
        "",
        "```bash",
        "git revert <merge-commit-sha>",
        "```",
        "",
        "## Test Plan",
        "",
        "- Review the run report and artifact diff listed above.",
        "- Run the project test suite relevant to the evolved artifact.",
        "- Run `python -m evolution.core.benchmark_gate --report <report.json>` when a benchmark gate is required.",
    ]
    return "\n".join(lines)


def _default_runner(command: list[str]) -> None:
    subprocess.run(command, check=True)


def prepare_pr(
    report: dict[str, Any],
    *,
    dry_run: bool = True,
    push: bool = False,
    open_pr: bool = False,
    branch: str | None = None,
    runner: Runner = _default_runner,
) -> dict[str, Any]:
    """Prepare PR metadata; remote mutation requires explicit flags."""
    title = build_pr_title(report)
    body = build_pr_body(report)
    result = {
        "title": title,
        "body": body,
        "branch": branch,
        "pushed": False,
        "opened_pr": False,
    }
    if dry_run:
        return result

    if push:
        if branch:
            runner(["git", "checkout", "-B", branch])
        runner(["git", "push", "-u", "origin", "HEAD"])
        result["pushed"] = True

    if open_pr:
        runner(["gh", "pr", "create", "--title", title, "--body", body])
        result["opened_pr"] = True

    return result


@click.command()
@click.option("--report", "report_path", required=True, type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option("--dry-run/--execute", default=True, show_default=True, help="Print title/body without mutating git or GitHub")
@click.option("--push", is_flag=True, help="Push the current branch; off by default")
@click.option("--open-pr", is_flag=True, help="Open a GitHub PR; off by default")
@click.option("--branch", default=None, help="Optional local branch name to create before pushing")
def main(
    report_path: Path,
    dry_run: bool,
    push: bool,
    open_pr: bool,
    branch: str | None,
) -> None:
    """Generate local-first PR title/body from an evolution run report."""
    report = json.loads(report_path.read_text())
    result = prepare_pr(report, dry_run=dry_run, push=push, open_pr=open_pr, branch=branch)
    click.echo(f"PR Title: {result['title']}")
    click.echo("")
    click.echo(result["body"])


if __name__ == "__main__":
    main()
