"""Local-first PR preparation for evolution run reports."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import click


def _format_score(value) -> str:
    try:
        return f"{float(value):+.3f}"
    except Exception:
        return "n/a"


def build_pr_text(report_path: Path) -> tuple[str, str]:
    """Build a deterministic PR title/body from a run report."""
    report = json.loads(Path(report_path).read_text())
    target = report.get("target", {})
    name = target.get("name", "unknown-target")
    scores = report.get("scores", {})
    constraints = report.get("constraints", {})
    gate = report.get("benchmark_gate") or {}
    gate_passed = gate.get("passed")
    gate_text = "PASS" if gate_passed is True else "FAIL" if gate_passed is False else "NOT RUN"

    title = f"Improve {name} via self-evolution"
    body = "\n".join([
        "## Summary",
        f"- Target: `{target.get('type', 'artifact')}` `{name}`",
        f"- Baseline holdout: {scores.get('baseline_holdout', 'n/a')}",
        f"- Optimized holdout: {scores.get('optimized_holdout', 'n/a')}",
        f"- Holdout delta: {_format_score(scores.get('holdout_delta'))}",
        "",
        "## Constraints",
        f"- All constraints passed: {constraints.get('all_passed', False)}",
        *[
            f"- {item.get('constraint_name')}: {'PASS' if item.get('passed') else 'FAIL'} — {item.get('message', '')}"
            for item in constraints.get("results", [])
        ],
        "",
        "## Benchmark gate",
        f"- Benchmark gate: {gate_text}",
        *[f"- Failure: {failure}" for failure in gate.get("failures", [])],
        *[f"- Warning: {warning}" for warning in gate.get("warnings", [])],
        "",
        "## Risk notes",
        "- Generated by hermes-agent-self-evolution; review the diff and report before promotion.",
        f"- Diff artifact: `{report.get('diff', {}).get('path', 'n/a')}`",
        "",
        "## Rollback",
        "- Revert this PR or restore the baseline artifact recorded in the run report.",
        "",
        "## Test plan",
        "- python -m pytest tests/ -q",
        f"- python -m evolution.core.benchmark_gate --report {report_path}",
    ])
    return title, body


def _run_git(args: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True, text=True)


@click.command()
@click.option("--report", "report_path", required=True, type=click.Path(exists=True, dir_okay=False, path_type=Path))
@click.option("--dry-run", is_flag=True, default=False, help="Print title/body without mutating git")
@click.option("--branch", default=None, help="Optional local branch name to create")
@click.option("--push", is_flag=True, default=False, help="Push the branch to origin")
@click.option("--open-pr", is_flag=True, default=False, help="Open a PR with gh (requires --push)")
def main(report_path: Path, dry_run: bool, branch: str | None, push: bool, open_pr: bool):
    """Prepare a PR body from a run report. Remote mutation is opt-in."""
    title, body = build_pr_text(report_path)

    if dry_run or (not branch and not push and not open_pr):
        click.echo(title)
        click.echo("\n" + body)
        return

    if open_pr and not push:
        raise click.ClickException("--open-pr requires --push")

    if branch:
        _run_git(["checkout", "-B", branch])
    if push:
        _run_git(["push", "-u", "origin", "HEAD"])
    if open_pr:
        subprocess.run([
            "gh", "pr", "create", "--title", title, "--body", body,
        ], check=True)


if __name__ == "__main__":
    main()
